###
# Site Settings
###

set :site_title, 'The Sites Title'
set :site_author, 'Site Author'
set :site_language, 'en-us'
set :site_url, 'http://url.domain'
set :site_description, 'The Description'
set :site_keywords, 'The Keywords'

# set analytics account
@analytics_account = false # or "UA-3769691-2"

###
# Compass
###

# Change Compass configuration
compass_config do |config|
  config.output_style     = :expanded
  config.line_comments    = true
  config.relative_assets  = true
end

###
# Haml
###

set :haml, {
  :ugly => true,
  :attr_wrapper => "\"",
  :format => :html5
}

###
# Use RedCarpet as markdown engine
###

set :markdown_engine, :redcarpet
set :markdown, :fenced_code_blocks => true, :autolink => true, :smartypants => true

###
# Page options, layouts, aliases and proxies
###

# Per-page layout changes:
#
# With no layout
# page "/path/to/file.html", :layout => false
#
# With alternative layout
# page "/path/to/file.html", :layout => :otherlayout
#
# A path which all have the same layout
# with_layout :admin do
#   page "/admin/*"
# end

# Proxy pages (http://middlemanapp.com/basics/dynamic-pages/)
# proxy "/this-page-has-no-template.html", "/template-file.html", :locals => {
#  :which_fake_page => "Rendering a fake page with a local variable" }


# Enable pretty URLs
# activate :directory_indexes

# Set index to "index.html"
# set :index_file, 'index.html'

# All URLs generated by link_to to be relative
## commented because conflict with pjax mode
# set :relative_links, true

###
# Helpers
###

# Automatic image dimensions on image_tag helper
# activate :automatic_image_sizes

# Reload the browser automatically whenever files change
activate :livereload, :host => '127.0.0.1'

# Methods defined in the helpers block are available in templates
# helpers do
#   def some_helper
#     "Helping"
#   end
# end

set :css_dir, 'css'
set :js_dir, 'js'
set :images_dir, 'images'

# Build-specific configuration
configure :build do
  puts "Building website and its structure..."

  # For example, change the Compass output style for deployment
  activate :minify_css

  # Minify Javascript on build
  activate :minify_javascript

  # Enable gzip compression
  # activate :gzip

  # Enable cache buster
  # activate :asset_hash

  # Use relative URLs
  # activate :relative_assets

  # Or use a different image path
  # set :http_prefix, "/Content/images/"

  # Compress PNGs after build
  # First: gem install middleman-smusher
  require "middleman-smusher"
  activate :smusher

  # Haml Config
  set :haml, {
    :ugly => true,
    :attr_wrapper => "\""
  }

  #Compass config
  compass_config do |config|
    config.line_comments    = false
    config.sass_options     = {:debug_info => false}
  end
end