# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman", "~>3.2.2"

# Live-reloading plugin
gem "middleman-livereload", "~> 3.1.0"

# For faster file watcher updates on Windows:
# gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

# Compile and compress for build
gem "middleman-smusher"

# Stylesheet parser engine
# gem "compass"
gem "sass"

# Javascript interpreter for ruby with V8
gem "therubyracer"

# HTML parser engine
gem "haml"

# JSON parser
gem "oj"

# Markdown engine
gem "redcarpet"